version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalogo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - catalogo

  db:
    image: postgres:13
    container_name: catalogo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - catalogo

  nginx:
    image: nginx:alpine
    container_name: catalogo-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - catalogo

networks:
  catalogo:
    driver: bridge

volumes:
  dbdata:
    driver: local
