version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: catalogo-service
    container_name: catalogo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
    networks:
      - catalogo-network

  db:
    image: postgres:13
    container_name: catalogo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - catalogo-network

networks:
  catalogo-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
