name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests with coverage
      run: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml

    - name: Run BDD tests
      run: vendor/bin/behat

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Check code coverage
      run: |
        echo "Checking for coverage.xml file..."
        if [ ! -f coverage.xml ]; then
          echo "coverage.xml file not found!"
          exit 1
        fi
        
        echo "coverage.xml file found. Extracting coverage data..."
        
        COVERED_ELEMENTS=$(xmllint --xpath "string(//project/metrics/@coveredelements)" coverage.xml)
        TOTAL_ELEMENTS=$(xmllint --xpath "string(//project/metrics/@elements)" coverage.xml)
        
        if [ -z "$COVERED_ELEMENTS" ] || [ -z "$TOTAL_ELEMENTS" ]; then
          echo "Failed to extract coverage data from coverage.xml"
          exit 1
        fi
        
        echo "Covered elements: $COVERED_ELEMENTS"
        echo "Total elements: $TOTAL_ELEMENTS"
        
        COVERAGE_PERCENTAGE=$(echo "scale=2; $COVERED_ELEMENTS / $TOTAL_ELEMENTS * 100" | bc)
        echo "Coverage percentage: $COVERAGE_PERCENTAGE%"
        
        if (( $(echo "$COVERAGE_PERCENTAGE < 80" | bc -l) )); then
          echo "Code coverage is below 80%: $COVERAGE_PERCENTAGE%"
          exit 1
        else
          echo "Code coverage is $COVERAGE_PERCENTAGE%"
        fi

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=LucasMinikel_fiap-tech-challenge-catalogo
          -Dsonar.organization=lucasminikel
          -Dsonar.sources=src
          -Dsonar.tests=tests,features
          -Dsonar.php.tests.reportPath=test-report.xml
          -Dsonar.php.coverage.reportPaths=coverage.xml